### ISSUE TITLE
Dependency Vulnerability: High Severity

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/OrionWebCoreStyleSheets#1]
## Problem

When installing the latest `@alaskaairux/orion-web-core-style-sheets (v0.3.516376651)`, npm audit throws 2 high severity dependency vulnerability warnings.

## Steps to reproduce

1. Open any npm project, or run `npm init` in an empty folder
2. Within said npm project, run `npm i @alaskaairux/orion-web-core-style-sheets`
3. Observe `found 2 high severity vulnerabilities`
4. Run `npm audit`
5. Observe vulnerability from `tar` package that was patched in `>=4.4.2`

## Possible Solution

`tar` is a dependency of `node-sass`, so it's possible that bumping the `node-sass` version in the project would solve this issue

**Comment by blackfalcon** [comment]
Dependency vulnerabilities are always popping up. This issue was addressed initially, but tar seems to be a consistent issue, especially with node-sass. 

The last binary 10 days ago as a nested vulnerability that was only issued 4 days ago. 

I am going to close this out as this is going to be an ongoing issue to address.
